# Window
WINDOW_BACKGROUND_COLOR = (36, 36, 36, 255)  # RGBA format
INITIAL_CAMERA_SCALE = 0.00106
IS_FULL_SCREEN = True
WINDOW_WIDTH = 1920
WINDOW_HEIGHT = 1080

# Agent & Game
IS_PLAY_SLEEP_ANIMATION = False
MUTATION_PROBABILITY = 10.0
FF_WEIGHT_THRESHOLD = 100000.0
POP_RETENTION_RATE = 5.0
POP_EXPO_PERCENTAGE = 10.0

# Simulation
NUM_FRAMES = 200
NUM_GAMES_IN_ROW = 35
NUM_GAMES = 1020
UNIT_FRAME_SIZE = 8.0
FRAME_SCALE = 10.0

# Resources
TILESET_PATH = "tiled/tileset.png"
TILE_SET_NAME = "tileset.png"

# Levels
LVL_BACKGROUND_SPRITE = "tiled/lvl2.png"
LVL_MAP_PATH = "tiled/lvl2.json"
LAYER_WALLS = "walls"
LAYER_DOOR = "door"
LAYER_KEYS = "keys"
LAYER_PLAYER = "player"
LAYER_SPIKES = "spikes"
LAYER_ENEMIES = "enemies"
